//
// NewsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NewsList: Codable, JSONEncodable, Hashable {

    public var status: String?
    //public var totalResults: Int
    public var news: [News]?

    public init(status: String? = nil, articles: [News]? = nil) {
        self.status = status
        //self.totalResults = totalResults
        self.news = articles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        //case totalResults
        case news
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        //try container.encode(totalResults, forKey: .totalResults)
        try container.encodeIfPresent(news, forKey: .news)
    }
}

